#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Ragnarok Gadgets Balloon ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Ragnarok Gadgets Balloon ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

#âœâœâœâœ This file handles all balloon related things.âœâœâœâœ
#âœâœâœâœ You can change anything here to be whatever custom stuff you want.âœâœâœâœ
#â˜ â˜ â˜ â˜  DO NOT CHANGE THE "Messages:" line as this will break the plugin.â˜ â˜ â˜ â˜ 

#Cow balloon placeholders.
Cow-Balloon-Name: '&2Cow &aBalloon'

#This is the lore that will be shown IN THE GUI  to the player if they do have permission to use the balloon
Has-Cow-Balloon-Use-Permission:
  - '&2This will show with perms'

#This is the lore that will be shown IN THE GUI to the player if they do NOT have permission to use the balloon
No-Cow-Balloon-Use-Permission:
  - '&4This will show without perms'


#See config.yml for permissions, and other plugin configurations
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/EHm6Ra3K
#â™ Thanks for downloading and have a wonderful day
#â™›â™›â™›â™›â™› End of messages.yml â™›â™›â™›â™›â™›
#This is the default file,