#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Ragnarok Gadgets ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Ragnarok Gadgets ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ
#Gadgets.Menu > Access to main gadgets menu
#Gadgets.Reload > Access to reload the configuration files
#a
#
#All balloons have a permission node that follows this format Gadgets.Balloon.enterMobNameHere
#You can also use the following wildcard permissions
#Gadgets.Balloon.* > Access to all balloons
#Gadgets.Balloon.Passive.* > Access to all balloons that are made of passive mobs
#Gadgets.Balloon.Hostile.* > Access to all balloons that are made of hostile mobs
#âœâœâœâœâœPermissionsâœâœâœâœâœ


#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/EHm6Ra3K
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default file.